name: Call Continuous Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  continuous-integration:
    uses: zoesgod/bygrace/.github/workflows/horusec.yml@maim

