name: SecurityPipeline
on: [push]
permissions: read-all

jobs:
  security-sast:
    name: horusec
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v4
      with: # Necessário quando habilitado o autores de commit
        fetch-depth: 0
    
    - name: Running Horusec Security
      run: |
        docker run -v /var/run/docker.sock:/var/run/docker.sock \
        -v $(pwd):/src/horusec \
        horuszup/horusec-cli:v2.9.0-beta.3 horusec start -p/src/horusec/ -j -w -e="true" --information-severity=true --log-level=warn -P $(pwd) --config-file-path=/src/horusec/horusec-config.json

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: ESLint Test
        uses: AbdulRehman-1/eslint-action@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          eslint-args: '--ignore-path=.gitignore'
          eslintrc: false # Set this to true if you want to use your own .eslintrc rules
          extensions: 'js,jsx,ts,tsx'
          auto-auto-fix-before-test: false # Set this to true if want to format and fix all the lint issue before testing
          annotations: true
